language: python
python:
#  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

# Requirements for running the package
install: pip install -r requirements.txt

#script: python setup.py test
script:
  - python tests/test_basic.py
  - python tests/test_functions.py

branches:
    only:
       - master

