language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# Requirements for running the package
install: pip install -r requirements.txt

script:
  - python tests/test_basic.py
  - python tests/test_functions.py


